name: Translate CSV
on:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  process-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pandas torch transformers sentencepiece protobuf==3.20

    - name: Run script
      run: |
        python extra/translator.py
    
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
